In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv("portland.csv")

In [3]:

df.head()

     Month Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114
0  1960-01                                                648
1  1960-02                                                646
2  1960-03                                                639
3  1960-04                                                654
4  1960-05                                                630

In [4]:
#ARIMA= auto regression integreted moving average

In [5]:
df.shape

(115, 2)

In [6]:
df.info

<bound method DataFrame.info of                                                  Month Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114
0                                              1960-01                                                648
1                                              1960-02                                                646
2                                              1960-03                                                639
3                                              1960-04                                                654
4                                              1960-05                                                630
..                                                 ...                                                ...
110                                            1969-03                                               1419
111                                            1969-04                                               1432
112                                            1969-05                                               1394
113                                            1969-06                                               1327
114  Portland Oregon average monthly bus ridership ...                                              n=114

[115 rows x 2 columns]>

In [7]:
df.dtypes

Month                                                                                         object
Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114    object
dtype: object

In [8]:
df.isnull().sum()

Month                                                                                         0
Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114    0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 2 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Month                                                                                       115 non-null    object
 1   Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114  115 non-null    object
dtypes: object(2)
memory usage: 1.9+ KB

In [10]:
df['Month']=pd.to_datetime(df['Month'],errors='coerce', format='%Y-%m')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 2 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Month                                                                                       114 non-null    datetime64[ns]
 1   Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114  115 non-null    object
dtypes: datetime64[ns](1), object(1)
memory usage: 1.9+ KB

In [12]:
df

         Month Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114
0   1960-01-01                                                648
1   1960-02-01                                                646
2   1960-03-01                                                639
3   1960-04-01                                                654
4   1960-05-01                                                630
..         ...                                                ...
110 1969-03-01                                               1419
111 1969-04-01                                               1432
112 1969-05-01                                               1394
113 1969-06-01                                               1327
114        NaT                                              n=114

[115 rows x 2 columns]

In [13]:
df.set_index('Month',inplace=True)

In [14]:

df.head()

           Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114
Month
1960-01-01                                                648
1960-02-01                                                646
1960-03-01                                                639
1960-04-01                                                654
1960-05-01                                                630

In [15]:
df.dtypes

Portland Oregon average monthly bus ridership (/100) January 1973 through June 1982, n=114    object
dtype: object

In [16]:
df['avg monthly busride']=df['avg monthly busride'].astype(int)

KeyError: ignored